version: "3.9"

services:
  web:
    container_name: web
    image: node:16.13
    depends_on:
      - api
    command: bash -c "yarn install && yarn dev"
    working_dir: /web
    volumes:
      - ./web:/web
    ports:
      - 3000:3000

  api:
    container_name: api
    image: node:16.13
    depends_on:
      - mongodb
    command: bash -c "yarn install && yarn dev"
    working_dir: /api
    volumes:
      - ./api:/api
    ports:
      - 3001:3001
    environment:
      HOST: 0.0.0.0
      SWAGGER_HOST: localhost
      DB_HOST: mongodb://mongodb:27017

  mongodb:
    container_name: mongodb
    image: mongo:4.2
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: blog
      MONGO_INITDB_ROOT_PASSWORD: blog
