version: "3.9"

services:
  web:
    container_name: web
    image: node:16.13
    depends_on:
      - api
    command: bash -c "yarn install && yarn dev"
    working_dir: /web
    volumes:
      - ./web:/web
    ports:
      - 3000:3000

  api:
    container_name: api
    image: node:16.13
    depends_on:
      - postgres
      - mongodb
    command: bash -c "yarn install && yarn dev"
    working_dir: /api
    volumes:
      - ./api:/api
    ports:
      - 3001:3001
    environment:
      HOST: 0.0.0.0
      SWAGGER_HOST: localhost
      MONGODB_HOST: mongodb://mongodb:27017
      POSTGRES_HOST: postgres
      POSTGRES_POST: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: partiu_treino_dev

  postgres:
    container_name: postgres
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  mongodb:
    container_name: mongodb
    image: mongo:4.2
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: blog
      MONGO_INITDB_ROOT_PASSWORD: blog
