version: "3.9"

services:
  web:
    build: ./web
    container_name: web
    depends_on:
      - api
    command: yarn dev
    volumes:
      - ./web:/web
    ports:
      - 3000:3000

  api:
    build: ./api
    container_name: api
    depends_on:
      - db
    command: yarn dev
    volumes:
      - ./api:/api
    ports:
      - 3001:3001
    environment:
      - HOST=0.0.0.0
      - DB_HOST=mongodb://db:27017

  db:
    container_name: db
    image: mongo:4.2
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: blog
      MONGO_INITDB_ROOT_PASSWORD: blog
